#!/usr/bin/env python3.5
import argparse
import pathlib

from andy.videoinfo import VideoInfo
from andy.util import Mood

args = argparse.ArgumentParser()
args.add_argument("--database", "-db", help="Location of the database file.")
args.add_argument("files", nargs="*", help="Entries to be deleted (by filename).")

options = vars(args.parse_args())

if not options["database"]:
    vi = VideoInfo.cwd()
else:
    vi = VideoInfo(options["database"])

if "files" not in options or not isinstance(options["files"], list) or options["files"] is None:
    print("{} No files specified.".format(Mood.sad()))
    raise ValueError

for filename in options["files"]:
    vi.deletefileentry(filename)
