#!/usr/bin/env ruby
require 'pathname'

require_relative 'andyrb/mood'
require_relative 'andyrb/util'
require_relative 'andyrb/videoinfo'

files = ARGV

raise 'No files specified' unless files.length >= 1

files.each do |f|
  path = Pathname.new(f)
  puts Mood.happy("Deleting #{path.basename}'s entry from the database.")
  del = GenerateVideoInfo::Videoinfo.all(filename: f.basename.to_s)
  del.destroy
end
