#!/usr/bin/python3.5
import pathlib
import magic

from andy.sortentries import sortentries

fileglob=pathlib.Path("/data/Private").rglob("videoinfo.sqlite")

filelist=[]

for filename in fileglob:
    with magic.Magic() as m:
        filetype=m.id_filename(str(filename))
        if "SQLite 3.x database" in filetype:
            filelist.append(str(filename.parent))

filelist=sortentries(filelist)

for filename in filelist:
    print(repr(filename))
