#!/usr/bin/env ruby
# frozen_string_literal: true

require 'io/console'
require 'openssl'
require 'date'

require_relative 'andyrb/core/cleanup'
require_relative 'andyrb/core/monkeypatch'
require_relative 'andyrb/options'

AndyCore.monkeypatch(AndyCore::Array::Cleanup)

# These are placeholders just to map out what data is going to be needed for this script.
CaPrivate = OpenSSL::PKey::EC.new(File.read('/home/evildarkarchon/certificates/andyECC.key'))
CaPublic = OpenSSL::PKey::EC.new(File.read('/home/evildarkarchon/certificates/andyECC2.crt'))
Enterprise_J_Private = OpenSSL::PKey::EC.new(File.read('/home/evildarkarchon/certificates/enterprise-j.key'))
Before = Time.now
Expire = Time.now + 730
