#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'find'

# require_relative 'andyrb/mood'
require_relative 'andyrb/util/hashfile'
require_relative 'andyrb/core/sort'
require_relative 'andyrb/core/cleanup'
require_relative 'andyrb/core/monkeypatch'
require_relative 'andyrb/videoinfo/database'
require_relative 'andyrb/videoinfo/filelist'
require_relative 'andyrb/videoinfo/genhash'
require_relative 'andyrb/options'

# Array.private_method_defined?(:include) ? Array.send(:include, AndyCore::Aray::Cleanup) : Array.include(AndyCore::Array::Cleanup)
# Array.private_method_defined?(:include) ? Array.send(:include, AndyCore::Aray::NatSort) : Array.include(AndyCore::Array::NatSort)
AndyCore.monkeypatch(Array, AndyCore::Array::Cleanup)
AndyCore.monkeypatch(Array, AndyCore::Array::NatSort)

opts = Options.new(ARGV.dup.cleanup) do |defaults|
  defaults[:reset_json] = false
  defaults[:reset_all] = false
  defaults[:verbose] = false
end
opts.construct! do |h, i|
  h.on('--reset-json', 'Purges the JSON caches for all databases found.') { i[:reset_json] = true }
  h.on('--reset-all', 'Resets the entire database.') { i[:reset_all] = true }
  h.on('--verbose', '-v', 'Make this script extra chatty.') { i[:verbose] = true }
end
def opts.directory
  outdir = @source.nil? || @source.empty? ? %w[/data/Private] : @source
  outdir.keep_if { |d| File.directory?(d) } if outdir.respond_to?(:keep_if)
  outdir
end

dir = opts.directory

DataMapper::Model.raise_on_save_failure = true
DataMapper::Logger.new($stdout, :debug) if opts[:verbose]

directories = []
if dir.respond_to?(:each)
  dir.each do |i|
    directories = VideoInfo::Database.find(i, opts[:verbose])
  end
else
  directories = VideoInfo::Database.find(dir, opts[:verbose])
end

filelist = []
initlist = []

if directories.respond_to?(:each)
  directories.each do |d|
    dbpath = Pathname.new(d).realpath
    dbpath = dbpath.dirname if dbpath.file?
    DataMapper.setup(:default, "sqlite:#{dbpath.join('videoinfo.sqlite')}")
    DataMapper.finalize
    VideoInfo::Database::Videoinfo.auto_migrate! unless opts[:reset_json]
    VideoInfo::Database::Videojson.auto_migrate! if [opts[:reset_json], opts[:reset_all]].any?

    initlist << dbpath.find.to_a
    initlist.cleanup!
    initlist.keep_if { |i| File.file?(i) }
    initlist.map!(&:to_s)

    filelist = VideoInfo.genfilelist(initlist).natsort
  end
else

  dbpath = Pathname.new(directories).realpath
  dbpath = dbpath.dirname if dbpath.file?

  DataMapper.setup(:default, "sqlite:#{dbpath.join('videoinfo.sqlite')}")
  DataMapper.finalize
  case
  when opts[:reset_json]
    VideoInfo::Database::Videojson.auto_migrate!
  when opts[:reset_all]
    VideoInfo::Database::Videoinfo.auto_migrate!
    VideoInfo::Database::Videojson.auto_migrate!
  else
    VideoInfo::Database::Videoinfo.auto_migrate!
  end

  initlist = dbpath.find.to_a
  initlist.keep_if(&:file?).map!(&:to_s).cleanup!.freeze

  filelist = VideoInfo.genfilelist(initlist).natsort
  filelist.freeze unless frozen?
end

digests = Util.hashfile(filelist).freeze

filelist.each do |file|
  filepath = Pathname.new(file).freeze
  FileUtils.touch(file) unless filepath.file?

  DataMapper.setup(:default, "sqlite:#{filepath.dirname.join('videoinfo.sqlite')}") if filepath.file?
  DataMapper.setup(:default, "sqlite:#{filepath.join('videoinfo.sqlite')}") if filepath.directory?
  gvi = VideoInfo::Database::Data.new(filepath.dirname.join('videoinfo.sqlite').to_s, opts[:verbose]) if filepath.file?
  gvi = VideoInfo::Database::Data.new(filepath.join('videoinfo.sqlite').to_s, opts[:verbose]) if filepath.directory?
  insert = VideoInfo::Database::Videoinfo.new

  jsondata = gvi.json(file, opts[:verbose])
  jsondata.freeze unless frozen

  VideoInfo.genhash(file, jsondata, digests) do |h|
    begin
      puts(Mood.happy { "Writing metadata for #{File.basename(file)}" })
      insert.attributes = h
      insert.save
    rescue DataMapper::SaveFailureError
      insert.errors.each { |e| puts e } if opts[:verbose]
    end
  end

  digests.delete(file)
end
