#!/usr/bin/env python3
import pathlib
import shutil
import logging
import systemd.journal as journal
import argparse
import lzma
import locale
from datetime import datetime
import os

from andy.util import Color, Program, Util

locale.setlocale(locale.LC_ALL, 'en_US.utf-8')

program = Program()
util = Util()

pgdump = shutil.which("pg_dump", mode=os.X_OK)

args = argparse.ArgumentParser()
args.add_argument("--cron", "-c", action="store_true", help="Activate this program in cron mode.")
options = (vars(args.parse_args()))

if not options["cron"]:
    colors = Color()

if options["cron"]:
    logformat = '%(asctime)-15s %(message)s'
    logging.basicConfig(format=logformat)

    log = logging.getLogger('backup')
    log.propagate = False
    log.addHandler(journal.JournalHandler(SYSLOG_IDENTIFIER="ttrss_backup"))
    log.setLevel(logging.DEBUG)

if not pgdump:
    print("{} pg_dump could not be found or is not executable.".format(colors.mood("sad")))
    raise FileNotFoundError

database = "feeds"
filename = str(pathlib.Path("/data/ttrssbackup").joinpath("feeds-{}.{}".format(datetime.now().strftime("%Y%m%d_%H%M"), "tar.xz")))

try:
    with open(filename, mode="wb") as db:
        if options["cron"]:
            log.info("Dumping Database.")
        else:
            print("{} Dumping Database.".format(colors.mood("happy")))

        data = program.returninfo([pgdump, "-C", "-F", "t", "-c", "--if-exists", "-d", database, "-U", "postgres"], string=False)

        if options["cron"]:
            log.info("Compressing Data.")
        else:
            print("{} Compressing Data.".format(colors.mood("happy")))
        compress = lzma.compress(data)
        if options["cron"]:
            log.info("Writing File: {}.".format(filename))
        else:
            print("{} Writing File: {}".format(colors.mood("happy"), filename))
        db.write(compress)
except KeyboardInterrupt:
    pathlib.Path(filename).unlink()
    raise

now = datetime.now()

files = util.sortentries(pathlib.Path("/data/ttrssbackup").rglob("feeds*.tar.xz"))

for filepath in files:
    then = datetime.fromtimestamp(filepath.stat().st_mtime)
    filetime = now - then
    if filetime.days > 14:
        if options["cron"]:
            log.info("Removing {} from backup directory.".format(filepath.name))
        else:
            print("{} Removing {} from backup directory.".format(colors.mood("neutral"), filepath.name))
        filepath.unlink()
