#!/usr/bin/env ruby
require 'optparse'
require 'subprocess'
require 'pathname'
require 'filemagic'
# require 'json'

require_relative 'andyrb/videoinfo_dm'
require_relative 'andyrb/mood'
require_relative 'andyrb/util'

class Options
  def self.parse(args)
    options = OpenStruct.new
    options.date = Time.now.strftime("%Y%m%d") # rubocop:disable Style/StringLiterals, Lint/UnneededDisable
    options.directory = Pathname.new('/data/Videos/Youtube')
    options.no_date = false
    options.force = false
    options.test_mkv = false
    options.no_stats = false

    optparse = OptionParser.new do |opts|
      opts.on('-d DIRECTORY', '--directory=DIRECTORY', 'Name of the directory to download to') { |dir| options.directory = Pathname.new(dir) }
      opts.on('-n', '--no-date', "Don't create a subdirectory with the date.") { options.no_date = true }
      opts.on('-f', '--force', "Don't add the url(s) to the list of succesfully downloaded videos or read from said list.") { options.force = true }
      opts.on('--test-mkv', 'Skip running youtube-dl and just test the statistics code.') { options.test_mkv = true }
      opts.on('--no-stats', "Don't calculate statistics for MKV files.") { options.no_stats = true }
    end
    optparse.parse!(args)
    options
  end
end
ARGV.compact! if ARGV.respond_to?(:compact!)
Args = Options.parse(ARGV)
Urls = ARGV

Args.directory = Args.directory + Args.date unless Args.no_date
YoutubeDL = Util::FindApp.which('youtube-dl')
MkvPropEdit = Util::FindApp.which('mkvpropedit')

Archive = Args.directory + 'downloaded.txt' if Args.no_date
Archive = Args.directory.parent + 'downloaded.txt' unless Args.no_date

puts Mood.sad("#{Args.directory} exists but is not a directory.") if Args.directory.exist? && !Args.directory.directory?
exit 1 if Args.directory.exist? && !Args.directory.directory?
puts Mood.happy("Creating Directory #{Args.directory}.") unless Args.directory.exist? && Args.directory.directory?
Args.directory.mkpath unless Args.directory.exist? && Args.directory.directory?
Dir.chdir(Args.directory.to_s)

case
when Args.force && !Args.test_mkv
  Util::Program.runprogram(%w(youtube-dl) + Urls)
  # print %w(youtube-dl) + Urls\n
when !Args.force && !Args.test_mkv
  Util::Program.runprogram(%W(youtube-dl --download-archive #{Archive}) + Urls)
  # print %W(youtube-dl --download-archive #{Args.directory}/downloaded.txt) + Urls\n
end

Files = Args.directory.find do |file|
  # puts file
  magic = FileMagic.new(:mime_type)
  whitelist = ['video/webm', 'video/x-matroska', 'audio/x-matroska']
  # puts magic.file(file.to_s)
  # puts whitelist.include?(magic.file(file.to_s))
  json = Util.recursive_symbolize_keys(GenerateVideoInfo.probe(file)) if file.file?
  # puts json.dig(:streams[0], :tags, :BPS) if json.respond_to?(:dig)
  case
  when Args.no_stats
    # puts 'Nope'
    Find.prune
  when !whitelist.include?(magic.file(file.to_s)) && file.file?
    # puts 'Nope'
    Find.prune
  when json.respond_to?(:dig) && json.dig(:streams[0], :tags, :BPS) && file.file?
    # puts 'Nope'
    Find.prune
  end
end
if Files.respond_to?(:each)
  Files.each do |file|
    puts Mood.happy("Adding statistic tags to #{file}.")
    Util::Program.runprogram(%W(#{MkvPropEdit} --add-track-statistics-tags #{file}))
  end
end
